### ISSUE TITLE
Add a timer above the main title in the home section

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#54]
Above the Geektoberfest'20 Heading, add a cool looking timer for when Geektoberfest ends (30 Oct).

You can add a label above the timer like "Ends in" , followed by the countdown

**Comment by Cypherdious89** [comment]
Can I do this ?

**Comment by sggts04** [comment]
@Priyansh-09 go ahead

**Comment by Aditya-2001** [comment]
I want to do this

**Comment by Cypherdious89** [comment]
Hey @sggts04 , I hope this is fine.

![Screenshot (5)](https://user-images.githubusercontent.com/55129015/95747768-99de5c80-0cb6-11eb-95a9-30ea8b2cf7d9.png)

**Comment by sggts04** [comment]
It looks decent but maybe it can be a little more minimal..? Its not fitting the vibe of the page is what I'm saying. The timer and its label can't be bigger than the title of the event itself :P

**Comment by Cypherdious89** [comment]
Now ?? 
Reduced the font-size from 5em to 4em. 😅

![Screenshot (6)](https://user-images.githubusercontent.com/55129015/95748969-76b4ac80-0cb8-11eb-882c-6185c9f8574f.png)

**Comment by sggts04** [comment]
Looks better, I feel the label(Events Ends In) needs to be smaller and more closer to the timer. Currently the Label is foreshadowing the timer. After that fix you can just submit a PR I think (with a live link)

**Comment by Cypherdious89** [comment]
@sggts04 I am getting this **warning** while generating GitHub live page link in console - _Loading failed for the <script> with source _https://priyansh-09.github.io/public/js/main.js_._

**_GitHub live Page link -_** https://priyansh-09.github.io/Geektoberfest-Main/
Due to this countdown timer is not loading due to that on GitHub live page.
Can you please help with this issue ?

**_On GitHub live page_**

![Screenshot 2020-10-12 202025](https://user-images.githubusercontent.com/55129015/95761126-8092db80-0cc9-11eb-86f4-a7e545dcd677.png)

**_On my PC (using VS Code Live Server)_**

![Screenshot (8)](https://user-images.githubusercontent.com/55129015/95761241-a7e9a880-0cc9-11eb-9b20-a7e1115f053c.png)

**Comment by sggts04** [comment]
You included the JS with location "/public/js/main.js" which is trying to look for the js file outside of your main repo.

Try using "public/js/main.js" instead

**Comment by Cypherdious89** [comment]
Thanks ! Fixed the issue. Creating a PR for this.
