### ISSUE TITLE
Redesign footer

### ISSUE THREAD

**Issue by sggts04** [GeekHaven/Geektoberfest-Main#83]
Following the colour scheme and design of the new navbar, redesign the footer using a similar design style, fonts etc. Try to keep it minimal.

**Comment by Cypherdious89** [comment]
Can I do this @sggts04 ??

**Comment by sggts04** [comment]
@Priyansh-09 go ahead

**Comment by Capt-Titanium** [comment]
@sggts04 can I work on this issue?

**Comment by Cypherdious89** [comment]
Hey @sggts04 is this footer looks fine ??

![Screenshot (1)](https://user-images.githubusercontent.com/55129015/95948704-b2618a80-0e0e-11eb-81d8-cec0072fd51f.png)


Give you feedback. 
I still have to add some hover effects to social icons and to fix that issue of cropping sections issue due to sticky navbar.

**Comment by sggts04** [comment]
Looks good, maybe you could use the same colour scheme as the navbar maybe? So that the site looks more uniform

**Comment by Cypherdious89** [comment]
How about this @sggts04 ?

![Screenshot (3)](https://user-images.githubusercontent.com/55129015/95949450-58fa5b00-0e10-11eb-854a-b9ad515f6c5f.png)

Color Scheme same as the navbar

**Comment by sggts04** [comment]
On second thought, the earlier version looks better 😂. Actually the dark version contrasted the the section above it well, so that version is better.
You can go ahead with the dark colour scheme version 👍
